seleniumstandalonechrome:
  image: selenium/standalone-chrome
  ports:
    - 4444:4444

runner:
  image: behatdev
  container_name: feature_runner
  ports:
    - 5900
  links:
    - seleniumstandalonechrome:hub
  command: ['tail', '-f', '/dev/null']
  volumes:
      - /Users/trtopcmu/behat/behat3dev/features:/behat3/features